######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 17 14:06:42 2013
######################################################################

TEMPLATE = lib
TARGET = zerai2c
DEPENDPATH += . src
INCLUDEPATH += .  

DEFINES += ZERA_MEAS_LIBRARY

# Input
#HEADERS += src/...
#SOURCES += src/...

target.path = /usr/lib
INSTALLS += target

