######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 17 14:06:42 2013
######################################################################

TEMPLATE = lib

include(../zera-classes.pri)

TARGET = zerameas
DEPENDPATH += . src
INCLUDEPATH += .  

DEFINES += ZERA_MEAS_LIBRARY

header_files.files = $$HEADERS
header_files.path = /usr/include/zera-classes/meas
INSTALLS += header_files
