#!/bin/sh
BASEPATH=`dirname $0`

# linefeed to xml opaque string
sed -i 's:&#xa;:___LF___:g' $2

echo "Writing $5"
xmlstarlet tr ${BASEPATH}/xsl-files/scpi-to-html.xsl -s zenuxVersion=$1 -s sessionXml=$2 -s sessionName="$3" -s createAdjustmentHtml=$4 $2 > "$5"

# replace xml opaque string by html linefeed
sed -i 's:___LF___\*:<br/>\&nbsp;\&nbsp;\&nbsp;\&nbsp;\&bull;:g' $5
sed -i 's:___LF___:<br/>\&nbsp;\&nbsp;\&nbsp;\&nbsp;:g' $5

# handcrafted bold '**'
sed -i -E 's:\*\*([^*]+)\*\*:<b>\1</b>:g' $5
sed -i -E 's:\_\_([^*]+)\_\_:<b>\1</b>:g' $5

# handcrafter italic '_'
#sed -i -E 's:_([^_]+)_:<i>\1</i>:g' $5
sed -i -E 's:\*([^ *][^*]*[^ *])\*:<i>\1</i>:g' $5

cssContents=$(cat ${BASEPATH}/css/main.css)
ESCAPED_DATA="$(echo "${cssContents}" | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/\$/\\$/g')"
sed -i ':a;N;$!ba;s|<style></style>|<style>'"$ESCAPED_DATA"'</style>|g' "$5"
