######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 17 14:03:10 2013
######################################################################

TEMPLATE = lib
TARGET = zeramath
DEPENDPATH += . src
INCLUDEPATH += .

DEFINES += ZERA_MATH_LIBRARY

# Input
#HEADERS += src/...
#SOURCES += src/...

target.path = /usr/lib
INSTALLS += target

