######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 17 14:03:10 2013
######################################################################

TEMPLATE = lib
TARGET = zeradev
DEPENDPATH += . src
INCLUDEPATH += . \
               /home/peter/C++/zera-classes/zera-comm/zera-i2c

DEFINES += ZERA_DEV_LIBRARY

LIBS += -L/home/peter/C++/zera-classes/zera-comm/build-zera-i2c-Qt_4_8_2_in_Pfad_temporär-Debug -lzerai2c

# Input
#HEADERS += src/...
#SOURCES += src/...

target.path = /usr/lib
INSTALLS += target

HEADERS += \
    i2ceeprom_p.h \
    F24LC256_p.h \
    dev_global.h \
    F24LC256.h

SOURCES += \
    i2ceeprom_p.cpp \
    F24LC256_p.cpp \
    F24LC256.cpp

