######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 17 14:03:10 2013
######################################################################

TEMPLATE = lib
TARGET = zeradev
DEPENDPATH += . src

DEFINES += ZERA_DEV_LIBRARY

# Input
#HEADERS += src/...
#SOURCES += src/...

target.path = /usr/lib
INSTALLS += target

HEADERS += \
    i2ceeprom_p.h \
    F24LC256_p.h \
    dev_global.h \
    F24LC256.h

SOURCES += \
    i2ceeprom_p.cpp \
    F24LC256_p.cpp \
    F24LC256.cpp


unix:!macx: LIBS += -L$$OUT_PWD/../zera-comm/zera-i2c/ -lzerai2c

INCLUDEPATH += $$PWD/../zera-comm/zera-i2c
DEPENDPATH += $$PWD/../zera-comm/zera-i2c

header_files.files = $$HEADERS
header_files.path = /usr/include/zeradev
INSTALLS += header_files
