#ifndef SUPPORTED_SOURCES_H
#define SUPPORTED_SOURCES_H

enum SupportedSourceTypes {
    SOURCE_MT_COMMON = 0,  // 3ph common
    SOURCE_MT_CURRENT_ONLY,
    SOURCE_MT_SINGLE_PHASE_ONLY,

    SOURCE_DEMO_FG_4PHASE, // AUX/harmonics

    SOURCE_TYPE_COUNT
};

#endif // SUPPORTED_SOURCES_H
