#ifndef HOTPLUGCONTROLSMODULECONFIGDATA_H
#define HOTPLUGCONTROLSMODULECONFIGDATA_H

namespace HOTPLUGCONTROLSMODULE
{

class cHotplugControlsModuleConfigData
{
public:
};

}

#endif // HOTPLUGCONTROLSMODULECONFIGDATA_H
