#ifndef CLIENTNETBASE_GLOBAL_H
#define CLIENTNETBASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CLIENTNETBASE_LIBRARY)
#  define CLIENTNETBASESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CLIENTNETBASESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CLIENTNETBASE_GLOBAL_H
