#ifndef ZERAPCBPROXY_GLOBAL_H
#define ZERAPCBPROXY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZERAPCBPROXY_LIBRARY)
#  define ZERAPCBPROXYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ZERAPCBPROXYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ZERAPCBPROXY_GLOBAL_H
