#ifndef IODEVICETYPES_H
#define IODEVICETYPES_H

enum IoDeviceTypes
{
    SERIAL_DEVICE_BROKEN,
    SERIAL_DEVICE_DEMO,
    SERIAL_DEVICE_ASYNCSERIAL,

    SERIAL_DEVICE_TYPE_COUNT
};

#endif // IODEVICETYPES_H
