#!/bin/sh

BASEPATH=`dirname $0`
mkdir -p "$1/html-docs"
MT_ADJUSTMENT_HTMLFILE="$1/html-docs/mt310s2-adjustment.html"
COM_ADJUSTMENT_HTMLFILE="$1/html-docs/com5003-adjustment.html"

for XMLFILE in "$1/scpi-xmls"/*.xml; do
    HTMLFILE=`echo "$XMLFILE" | sed '-e s:\.xml:\.html:g' '-e s:scpi-xmls:html-docs:g'`
    echo "Writing $HTMLFILE"
    xmlstarlet tr ${BASEPATH}/xsl-files/scpi-to-html.xsl -s zenuxVersion="$2" sessionXml="$XMLFILE" "$XMLFILE" > "$HTMLFILE"
done

XMLFILE="$1/scpi-xmls/mt310s2-meas-session.xml"
echo "Writing $MT_ADJUSTMENT_HTMLFILE"
xmlstarlet tr ${BASEPATH}/xsl-files/scpi-to-html.xsl -s zenuxVersion="$2" -s sessionXml=$XMLFILE -s adjustmentOutput="true" "$XMLFILE" > "$MT_ADJUSTMENT_HTMLFILE"

XMLFILE="$1/scpi-xmls/com5003-meas-session.xml"
echo "Writing $COM_ADJUSTMENT_HTMLFILE"
xmlstarlet tr ${BASEPATH}/xsl-files/scpi-to-html.xsl -s zenuxVersion="$2" -s sessionXml=$XMLFILE -s adjustmentOutput="true" "$XMLFILE" > "$COM_ADJUSTMENT_HTMLFILE"
