#!/bin/sh

BASEPATH=`dirname $0`
mkdir -p "$1/html-docs"
ADJUSTMENT_HTMLFILE="$1/html-docs/adjustment.html"

for XMLFILE in `find "$1/scpi-xmls" -name '*.xml'`; do
    HTMLFILE=`echo "$XMLFILE" | sed '-e s:\.xml:\.html:g' '-e s:scpi-xmls:html-docs:g'`
    echo "Writing $HTMLFILE"
    xmlstarlet tr ${BASEPATH}/xsl-files/scpi-to-html.xsl -s sessionXml="$XMLFILE" "$XMLFILE" > "$HTMLFILE"
done

echo "Writing $ADJUSTMENT_HTMLFILE"
xmlstarlet tr ${BASEPATH}/xsl-files/scpi-to-html.xsl -s sessionXml=$1/scpi-xmls/mt310s2-meas-session.xml -s adjustmentOutput="true" "$XMLFILE" > "$ADJUSTMENT_HTMLFILE"
