name: Build and unittest
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Recreate build caches"]
    branches: [master]
    types:
      - completed
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc]

    container:
      image: schnitzeltony/fedora-qt5:32
    steps:
      - name: Echo github environment
        run: |
          echo "Home: $HOME"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Event name: "${{ github.event_name }}
          echo "CPUs: $(getconf _NPROCESSORS_ONLN)"

      # Prepare source code for incremental build
      - name: Download source artifact last build
        if: ${{ github.event_name != 'workflow_dispatch' && github.event_name != 'schedule' }}
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: recreateBuildCaches.yml
          name: source-cache-${{ matrix.compiler }}
          check_artifacts: true
        continue-on-error: true

      - name: Untar source files last build
        run: |
          mkdir -p "$GITHUB_WORKSPACE"
          if [ -e source-cache-files.tar.xz ]; then
            tar -xf source-cache-files.tar.xz -C /
            rm source-cache-files.tar.xz
          else
            echo 'source-cache-files.tar.xz not found'
          fi

      - name: Checkout git
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Prepare last build files for incremental build
      - name: Download build artifact
        if: ${{ github.event_name != 'workflow_dispatch' && github.event_name != 'schedule' }}
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: recreateBuildCaches.yml
          name: build-cache-${{ matrix.compiler }}
          check_artifacts: true
        continue-on-error: true

      - name: Untar build files
        run: |
          mkdir -p "$HOME/targetbuild"
          if [ -e build-cache-files.tar.xz ]; then
            tar -xf build-cache-files.tar.xz -C /
            rm build-cache-files.tar.xz
          else
            echo 'build-cache-files.tar.xz not found'
          fi

      # Get zera-metaproject sysroot
      # * mandatory
      # * zera-metaproject's generator workflow name must be set
      - name: Download zera-metaproject's install artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          repo: ZeraGmbH/zera-metaproject
          name: install-artifact
          workflow: buildAndExportArtifact.yml

      - name: Untar zera-metaproject's install artifact
        run: |
            tar -xf install_files.tar.xz -C /
            rm install_files.tar.xz

      # Build & Unitttest
      - name: Build
        run: |
          mkdir -p "$HOME/targetbuild"
          cd "$HOME/targetbuild"

          if [ "${{ matrix.compiler }}" == "clang" ]; then
            export CC=clang
            export CXX=clang++
          fi
          cmake $GITHUB_WORKSPACE \
           -DCMAKE_PREFIX_PATH="$HOME/install/usr;/usr" \
           -DCMAKE_INSTALL_PREFIX:PATH="$HOME/install/usr" \
           -DCMAKE_INSTALL_SYSCONFDIR="$HOME/install/etc"
           make -j $(getconf _NPROCESSORS_ONLN)
           make -j $(getconf _NPROCESSORS_ONLN) install

      - name: Unittest
        run: |
          cd "$HOME/targetbuild"
          export QT_QPA_PLATFORM=offscreen
          ctest -V

