name: Build and unittest
on:
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        compiler: [gcc, clang]

    container:
      image: schnitzeltony/fedora-qt5:32
    steps:
      - name: Echo github environment
        run: |
          echo "Home: $HOME"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "CPUs: $(getconf _NPROCESSORS_ONLN)"

      # Prepare source code for incremental build
      - name: Download source artifact last build
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: ZeraGmbH/zera-classes
          name: source-artifact-${{ matrix.compiler }}
          workflow: buildAndTest.yml
        continue-on-error: true

      - name: Untar source files last build
        run: |
          mkdir -p "$GITHUB_WORKSPACE"
          if [ -e source_files.tar.xz ]; then
            tar -xf source_files.tar.xz -C /
            rm source_files.tar.xz
          fi

      - name: Checkout git
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Prepare last build files for incremental build
      - name: Download build artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: ZeraGmbH/zera-classes
          name: build-artifact-${{ matrix.compiler }}
          workflow: buildAndTest.yml
        continue-on-error: true

      - name: Untar build files
        run: |
          mkdir -p "$HOME/targetbuild"
          if [ -e build_files.tar.xz ]; then
            tar -xf build_files.tar.xz -C /
            rm build_files.tar.xz
          fi

      # Prepare last install files for incremental build
      - name: Download install artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: ZeraGmbH/zera-classes
          name: install-artifact-${{ matrix.compiler }}
          workflow: buildAndTest.yml
        continue-on-error: true

      - name: Untar install files
        run: |
          if [ -e install_files.tar.xz ]; then
            tar -xf install_files.tar.xz -C /
            rm install_files.tar.xz
          fi

      # Get zera-metaproject sysroot
      - name: Download zera-metaproject's install artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: ZeraGmbH/zera-metaproject
          name: install-artifact
          workflow: buildAndExportArtifact.yml

      - name: Untar zera-metaproject's install artifact
        run: |
            tar -xf install_files.tar.xz -C /
            rm install_files.tar.xz

      - name: Build
        run: |
          mkdir -p "$HOME/targetbuild"
          cd "$HOME/targetbuild"

          if [ "${{ matrix.compiler }}" == "clang" ]; then
            export CC=clang
            export CXX=clang++
          fi
          cmake $GITHUB_WORKSPACE \
           -DCMAKE_PREFIX_PATH="$HOME/install/usr;/usr" \
           -DCMAKE_INSTALL_PREFIX:PATH="$HOME/install/usr" \
           -DCMAKE_INSTALL_SYSCONFDIR="$HOME/install/etc"
           make -j $(getconf _NPROCESSORS_ONLN)

      - name: Unittest
        run: |
          cd "$HOME/targetbuild"
          ctest -V

      # Keep sources for incremental checkout
      - name: Tar sources
        run: |
          tar -c -I 'xz -T0' -f $HOME/source_files.tar.xz "$GITHUB_WORKSPACE"

      - name: Upload source artifact
        uses: actions/upload-artifact@v3
        with:
          name: source-artifact-${{ matrix.compiler }}
          path: /github/home/source_files.tar.xz

      # Keep build files for incremental build
      - name: Tar build files
        run: |
          tar -c -I 'xz -T0' -f $HOME/build_files.tar.xz "$HOME/targetbuild"

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact-${{ matrix.compiler }}
          path: /github/home/build_files.tar.xz

      # Keep install files for incremental build / submodule actions
      - name: Tar install files
        run: |
          tar -c -I 'xz -T0' -f $HOME/install_files.tar.xz "$HOME/install"

      - name: Upload install artifact
        uses: actions/upload-artifact@v3
        with:
          name: install-artifact-${{ matrix.compiler }}
          path: /github/home/install_files.tar.xz
